@LockNote_Api_HostAddress = https://localhost:5001

### Create a note
POST {{LockNote_Api_HostAddress}}/api/notes
Content-Type: application/json

{
  "content": "This is a test note",
  "readBeforeDelete": 3,
  "password": "mypassword"
}

### Get a note
@Note_Id = rh4Vok0GXR
POST {{LockNote_Api_HostAddress}}/api/notes/{{Note_Id}}
Content-Type: application/json

{
  "password": "mypassword"
}
