name: Deploy to Azure

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download build artifacts of API and Frontend
        uses: actions/download-artifact@v4
        with:
          name: build-front-and-api

      - name: Download build artifacts of Function App
        uses: actions/download-artifact@v4
        with:
          name: build-func-app

      - name: Create infrastructure
        run: |
          az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}

          deploymentOutputs=$(az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infrastructure/main.bicep \
            --query "properties.outputs" -o json)

          # Extract the connection string from the outputs
          connectionString=$(echo $deploymentOutputs | jq -r '.connectionString.value')

          # Export the connection string as a GitHub Actions environment variable
          echo "connectionString=${connectionString}" >> $GITHUB_ENV

      - name: Use the Connection String
        run: |
          echo "Using the connection string..."
          echo "Connection String: ${{ env.connectionString }}"

      - name: Get Publish Profile
        id: get-publish-profile
        run: |
          az webapp deployment list-publishing-profiles \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --output json > publishProfile.json

          # Extract the profile content and encode it for safe handling
          publish_profile=$(cat publishProfile.json | jq -r '.[0].publishingProfile')
          echo "PUBLISH_PROFILE=$publish_profile" >> $GITHUB_ENV

          echo ${{ env.PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App (API and Frontend)
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src/publish

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "./src/LockNote.FuncApp/publish-func-app/"
