name: Deploy to Azure

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
      AZURE_RESOURCE_GROUP:
        required: true
      AZURE_LOCATION:
        required: true
    inputs:
      AZURE_WEBAPP_NAME:
        required: true
        type: string
      AZURE_FUNCTIONAPP_NAME:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print part of secret
        run: |
          echo "Secret first 5 characters: ${SECRET:0:5}"
        env:
          SECRET: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if secret is available
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "Secret is empty!"
            exit 1
          else
            echo "Secret is available"
          fi

      - name: Login to Azure
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download build artifacts of API and Frontend
        uses: actions/download-artifact@v4
        with:
          name: build-front-and-api

      - name: Download build artifacts of Function App
        uses: actions/download-artifact@v4
        with:
          name: build-func-app

      - name: Create infrastructure
        run: |
          az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}

          deploymentOutputs=$(az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infrastructure/main.bicep \
            --query "properties.outputs" -o json)

          # Extract the connection string from the outputs
          connectionString=$(echo $deploymentOutputs | jq -r '.connectionString.value')

          # Export the connection string as a GitHub Actions environment variable
          echo "connectionString=${connectionString}" >> $GITHUB_ENV

      - name: Get Publish Profile
        id: get-publish-profile
        run: |
          az webapp deployment list-publishing-profiles \
            --name ${{ inputs.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --output json > publishProfile.json

          # Extract the profile content and encode it for safe handling
          publish_profile=$(cat publishProfile.json | jq -r '.[0].publishingProfile')
          echo "PUBLISH_PROFILE=$publish_profile" >> $GITHUB_ENV

      - name: Deploy to Azure Web App (API and Frontend)
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.AZURE_WEBAPP_NAME }}
          slot-name: "production"
          publish-profile: ${{ env.PUBLISH_PROFILE }}
          package: ./src/publish

      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
          package: "./src/LockNote.FuncApp/publish-func-app/"
