name: Deploy Bicep to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod # Specify the environment here

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Deploy Bicep
      - name: Deploy Bicep File
        run: |
          az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location ${{ secrets.AZURE_LOCATION }}
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --template-file infrastructure/main.bicep

      # Step 4: Build and Deploy React Frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        working-directory: ./client/lock-note-web-app
        run: npm install # todo ci

      - name: Build React App
        working-directory: ./client/lock-note-web-app
        run: npm run build

      - name: Deploy React App to Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "./client/lock-note-web-app" # Location of React app
          output_location: "./client/lock-note-web-app/build" # Build output folder

      # Step 5: Deploy .NET API to App Service
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Publish API
        working-directory: ./LockNote.Api
        run: dotnet publish -c Release -o ./publish

      - name: Deploy API to Azure App Service
        uses: Azure/webapps-deploy@v2
        with:
          app-name: "LockNote" # Azure App Service name
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./LockNote.Api/publish
