name: Deploy Lock-note to Azure

on:
  pull_request: # Trigger the workflow on pull requests
    branches:
      - main
  push: # Trigger the workflow on push to main
    branches:
      - pipeline-refactor
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy-test:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      AZURE_WEBAPP_NAME: "${{ vars.AZURE_WEBAPP_NAME }}-test"
      AZURE_FUNCTIONAPP_NAME: "${{ vars.AZURE_FUNCTIONAPP_NAME }}-test"
      COSMOS_DB_ACCOUNT_NAME: "${{ vars.COSMOS_DB_ACCOUNT_NAME }}-test"
      FUNCTION_STORAGE_ACCOUNT_NAME: "${{ vars.FUNCTION_STORAGE_ACCOUNT_NAME }}-test"

  tests:
    needs: deploy-test
    uses: ./.github/workflows/tests.yml
    # TODO: add url to fronend for tests

  deploy:
    needs: [build, tests]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
      COSMOS_DB_ACCOUNT_NAME: ${{ vars.COSMOS_DB_ACCOUNT_NAME }}
      FUNCTION_STORAGE_ACCOUNT_NAME: ${{ vars.FUNCTION_STORAGE_ACCOUNT_NAME }}
