name: Deploy Lock-note to Azure

on:
  pull_request: # Trigger the workflow on pull requests
    branches:
      - main
  push: # Trigger the workflow on push to main
    branches:
      - pipeline-refactor
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    uses: ./.github/workflows/build.yml

  tests:
    needs: build
    uses: ./.github/workflows/tests.yml

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}
      AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
