name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Playwright Browsers
        working-directory: ./src
        run: dotnet playwright install || npx playwright install

      - name: Run Playwright Tests
        working-directory: ./src
        run: dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: TestResults/
