name: Run Unit and End-to-End Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download build artifacts of API and Frontend
        uses: actions/download-artifact@v4.1.8
        with:
          name: build-front-and-api
          path: ./build-front-and-api

      - name: Download build artifacts of Function App
        uses: actions/download-artifact@v4.1.8
        with:
          name: build-func-app
          path: ./build-func-app

      - name: Run Unit Tests
        run: |
          dotnet test ./src/LockNote.Tests/LockNote.Tests.csproj --logger "trx;LogFileName=test-results.trx"

      - name: Install Playwright Browsers (Using PowerShell)
        run: pwsh bin/Release/net8.0/playwright.ps1 install
        working-directory: ./src/LockNote.End2EndTests

      - name: Run Playwright Tests
        working-directory: ./src
        run: dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: TestResults/
