name: Tests

on:
  workflow_call:

jobs:
  tests:
    runs-on: windows-latest

    steps:
      - name: Install Playwright Browsers (Using PowerShell)
        run: pwsh bin/Release/net8.0/playwright.ps1 install
        working-directory: ./src/LockNote.End2EndTests

      - name: Run Playwright Tests
        working-directory: ./src
        run: dotnet test --logger "trx;LogFileName=test-results.trx"

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-test-results
          path: TestResults/
